import type { NextPage } from 'next'
import Head from 'next/head'
import {Box} from "@material-ui/core"
import Layout from "../src/Layouts/Layouts";
import Areas from "../src/components/Areas/Areas";

const Area: NextPage = () => {
    return (
        <Box>
            <Head>
                <title>Areas </title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <Layout>
                <Areas />
            </Layout>
        </Box>
    )
}

export default Area;
