import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import {Box} from "@material-ui/core"
import Layout from "../src/Layouts/Layouts";
import HomePage from "../src/components/Home/HomePage";

const Home: NextPage = () => {
  return (
    <Box>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Layout>
          <HomePage />
      </Layout>
    </Box>
  )
}

export default Home;
