import type { NextPage } from 'next'
import Head from 'next/head'
import {Box} from "@material-ui/core"
import LoginComponent from "../src/ReusiableComponents/Login/Login";

const Login: NextPage = () => {
    return (
        <Box>
            <Head>
                <title>Login </title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <LoginComponent />
        </Box>
    )
}

export default Login;
