import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import {Box} from "@material-ui/core"
import Layout from "../src/Layouts/Layouts";
import News from "../src/components/News/News"
const Shop: NextPage = () => {
    return (
        <Box>
            <Head>
                <title>Latest News </title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <Layout>
               <News />
            </Layout>
        </Box>
    )
}

export default Shop;