import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import {Box} from "@material-ui/core"
import Layout from "../src/Layouts/Layouts";
import TableComponent from "../src/components/Table/Table";

const Shop: NextPage = () => {
    return (
        <Box>
            <Head>
                <title>Table </title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <Layout>
                <TableComponent />
            </Layout>
        </Box>
    )
}

export default Shop;
